// Official sender domains only. Consumer mailbox and tenant-hosting domains are
// deliberately absent: a Gmail/Outlook address identifies a person, not Google/Microsoft.
export const SENDER_BRANDS = Object.freeze([
  { id: 'apple', domains: ['apple.com'] },
  { id: 'microsoft', domains: ['microsoft.com', 'microsoftemail.com', 'microsoftstore.com'] },
  { id: 'google', domains: ['google.com', 'withgoogle.com'] },
  { id: 'github', domains: ['github.com'] },
  { id: 'paypal', domains: ['paypal.com', 'paypal.co.uk', 'paypal.de', 'paypal.fr'] },
  { id: 'netflix', domains: ['netflix.com'] },
  { id: 'spotify', domains: ['spotify.com'] },
  { id: 'steam', domains: ['steampowered.com', 'steamcommunity.com'] },
  { id: 'telegram', domains: ['telegram.org'] },
  { id: 'discord', domains: ['discord.com', 'discordapp.com'] },
  { id: 'dropbox', domains: ['dropbox.com', 'dropboxmail.com'] },
  { id: 'facebook', domains: ['facebook.com', 'facebookmail.com', 'meta.com'] },
  { id: 'instagram', domains: ['instagram.com'] },
  { id: '1password', domains: ['1password.com'] },
  { id: 'airbnb', domains: ['airbnb.com'] },
  { id: 'aliexpress', domains: ['aliexpress.com'] },
  { id: 'alibabacloud', domains: ['alibabacloud.com'] },
  { id: 'anthropic', domains: ['anthropic.com'] },
  { id: 'asus', domains: ['asus.com'] },
  { id: 'atlassian', domains: ['atlassian.com'] },
  { id: 'bilibili', domains: ['bilibili.com'] },
  { id: 'bitbucket', domains: ['bitbucket.org'] },
  { id: 'bitwarden', domains: ['bitwarden.com'] },
  { id: 'cloudflare', domains: ['cloudflare.com'] },
  { id: 'coursera', domains: ['coursera.org'] },
  { id: 'dell', domains: ['dell.com'] },
  { id: 'digitalocean', domains: ['digitalocean.com'] },
  { id: 'docker', domains: ['docker.com'] },
  { id: 'douban', domains: ['douban.com'] },
  { id: 'duolingo', domains: ['duolingo.com'] },
  { id: 'ea', domains: ['ea.com'] },
  { id: 'ebay', domains: ['ebay.com', 'ebay.co.uk', 'ebay.de'] },
  { id: 'epicgames', domains: ['epicgames.com'] },
  { id: 'figma', domains: ['figma.com'] },
  { id: 'gitlab', domains: ['gitlab.com'] },
  { id: 'huawei', domains: ['huawei.com'] },
  { id: 'intel', domains: ['intel.com'] },
  { id: 'jetbrains', domains: ['jetbrains.com'] },
  { id: 'kickstarter', domains: ['kickstarter.com'] },
  { id: 'lenovo', domains: ['lenovo.com'] },
  { id: 'medium', domains: ['medium.com'] },
  { id: 'netlify', domains: ['netlify.com'] },
  { id: 'notion', domains: ['notion.so', 'makenotion.com'] },
  { id: 'nvidia', domains: ['nvidia.com'] },
  { id: 'patreon', domains: ['patreon.com'] },
  { id: 'pinterest', domains: ['pinterest.com'] },
  { id: 'playstation', domains: ['playstation.com'] },
  { id: 'reddit', domains: ['reddit.com', 'redditmail.com'] },
  { id: 'samsung', domains: ['samsung.com'] },
  { id: 'signal', domains: ['signal.org'] },
  { id: 'sony', domains: ['sony.com'] },
  { id: 'substack', domains: ['substack.com'] },
  { id: 'synology', domains: ['synology.com'] },
  { id: 'tailscale', domains: ['tailscale.com'] },
  { id: 'taobao', domains: ['taobao.com'] },
  { id: 'trello', domains: ['trello.com'] },
  { id: 'twitch', domains: ['twitch.tv'] },
  { id: 'uber', domains: ['uber.com'] },
  { id: 'udemy', domains: ['udemy.com'] },
  { id: 'vercel', domains: ['vercel.com'] },
  { id: 'wechat', domains: ['wechat.com', 'weixin.qq.com'] },
  { id: 'whatsapp', domains: ['whatsapp.com'] },
  { id: 'xiaomi', domains: ['xiaomi.com', 'mi.com'] },
  { id: 'zhihu', domains: ['zhihu.com'] },
  { id: 'zoom', domains: ['zoom.us', 'zoom.com'] },
  { id: 'baidu', domains: ['baidu.com'] },
]);

export function senderBrandForDomain(domain) {
  if (typeof domain !== 'string') return null;
  const normalized = domain.toLowerCase().replace(/[.]$/, '');
  return SENDER_BRANDS.find(brand => brand.domains.some(official =>
    normalized === official || normalized.endsWith(`.${official}`)
  )) || null;
}
